### ISSUE TITLE
Touch Gestures not having consistent input

### ISSUE THREAD

**Issue by xSamel-The-Camelx** [Mrcubix/Touch-Gestures#14]
Whenever a Touch Gesture input + any cursor movement happens (ie from a mouse or from having a pen on the same tablet) some Touch Gesture inputs are dropped. 
Have only tested with Scroll bound to Paning so far.
This seems to be a linux only issue, the very limited testing I did on windows seemed to work as intended.

**Comment by Mrcubix** [comment]
Pretty much all touch gestures are timing sensitives, which could be an issues if a pen & touch is used at the same time.

As for moving the mouse causing issues?
That is very odd, not something i or a couple other people (who ended up ghosting me when testing feedback was needed) noticed.

Will investigate, but maybe i should implement & provide a way in the app to test gestures and see when a gesture has started / bind was activated / touch was released (sometimes without any being involved)

**Comment by Mrcubix** [comment]
Could you check if the same issue happens with single touch gesture using your pen.
(It should be a separate filter in the same tab and the setup knterface should be different)

**Comment by xSamel-The-Camelx** [comment]
Not sure If I did everything right. So I'll explain what I did.

Uninstalled all plugins but Scroll Bindings and Enhanced Out put Modes. extracted the contents of the plugin you linked into `~/.config/OpenTabletDriver/Plugins/Enhanced Output Modes`. Ran the UX. Didnt have Pen Gestures so closed everything, redid extracting the plugin, and opened the OTD Daemon, GUI and your Touch Gestures UX. Enabled Pen Gestures and disabled Touch Gestures. Setup Scroll up bound to Pan UP and tested it. It worked for the first test, but Left click was still bound to the tip. Went to disable it and the scroll speed was a fraction of what it was before. I think I just closed and reopened the UX and added Scroll Down to Pan Down and it crashed



``
samelthecamel@Camel-Comp ~/OTDTesting $ ./Touch-Gestures.UX.Desktop
Unhandled exception. System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at TouchGestures.UX.ViewModels.BindingsOverviewViewModel.OnSetupCompleted(Object sender, GestureAddedEventArgs e) in /home/runner/work/Touch-Gestures/Touch-Gestures/Touch-Gestures.UX/ViewModels/BindingsOverviewViewModel.cs:line 291
   at TouchGestures.UX.ViewModels.GestureSetupWizardViewModel.OnSetupCompleted(Object sender, EventArgs e) in /home/runner/work/Touch-Gestures/Touch-Gestures/Touch-Gestures.UX/ViewModels/GestureSetupWizardViewModel.cs:line 156
   at TouchGestures.UX.ViewModels.Controls.Setups.GestureSetupViewModel.OnSetupCompleted(GestureSetupViewModel sender) in /home/runner/work/Touch-Gestures/Touch-Gestures/Touch-Gestures.UX/ViewModels/Controls/Setups/GestureSetupViewModel.cs:line 200
   at TouchGestures.UX.ViewModels.Controls.Setups.SwipeSetupViewModel.DoComplete() in /home/runner/work/Touch-Gestures/Touch-Gestures/Touch-Gestures.UX/ViewModels/Controls/Setups/SwipeSetupViewModel.cs:line 151
   at CommunityToolkit.Mvvm.Input.RelayCommand.Execute(Object parameter)
   at Avalonia.Controls.Button.OnClick()
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers, IInputElement hitTest)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   at TouchGestures.UX.Desktop.Program.Main(String[] args) in /home/runner/work/Touch-Gestures/Touch-Gestures/Touch-Gestures.UX.Desktop/Program.cs:line 13
Aborted
samelthecamel@Camel-Comp ~/OTDTesting $
``
somewhere in there my mouse was losing some functionally, think it didn't want to scroll while the Pen was touching the tablet but I don't remember the details. 

Ill continue to test and come back with anymore notable results

**Comment by Mrcubix** [comment]
> Uninstalled all plugins but Scroll Bindings and Enhanced Out put Modes. extracted the contents of the plugin you linked into ~/.config/OpenTabletDriver/Plugins/Enhanced Output Modes

Odd, should only have to extract the release & overwrite files when necessary in the `OTD.EnhancedOutputMode` directory, then restart the service (Linux) or restart the daemon (Windows).

The exception you encountered only occur because the wizard somehow stopped being.

![image](https://github.com/user-attachments/assets/44d6bcd2-3b60-46b8-b419-e0d5dddae0d4)

> Modifying the Tip Binding at all provides the slower speed, using this site for my scroll testing

Abnormal to say the least.

> remaking the Gestures fixed the slow scrolling speeds

This plugin stores gestures settings in a file named `Touch-Gestures.json`, it should be created in whatever directory OpenTabletDriver consider "AppData" : 

- `$XDG_CONFIG_HOME/OpenTabletDriver`, 
- `~/.config/OpenTabletDriver`

Could try backing it up, starting fresh and see if it occurs.

> The same behavior I had with the touch is happening with the pen. But also happening with itself

If you can get a recording and see it here, or at least a recording of the recorded inputs, via OTD's Tablet debugger 
(`Tablet` -> `Tablet debugger`), so i can throw it at the unit test and see what behavior comes out of it.

**Comment by xSamel-The-Camelx** [comment]
> If you can get a recording and see it here

Accidentally streamed it instead of recording it, hopefully it still works out.
https://www.twitch.tv/videos/2288301273
The super slow speeds were when I was using the mouse at the same time as Pen Gestures
Pen at greater than 0 sens with Pen Gestures would be about half rate
I only had scroll up bound and had to reset the binding in the UX every time I changed the Sensitivity
 

> Could try backing it up, starting fresh and see if it occurs.

Did not fix anything. fixing it is as simple as clicking the 3 dots then hitting apply then save and its good.

> The only ways NextViewModel could not be the setup wizard are :

It might have crashed around the time I was making the down scroll binding. I don't remember exactly. But I do know that down scroll binding wasn't there when I opened it back up after the crash.

**Comment by Mrcubix** [comment]
> Pen at greater than 0 sens with Pen Gestures would be about half rate
> Only way to get proper gesture input with the pen is by dropping the sensitivity to 0

It shouldn't be affected by pen sens, since it works using the raw coordinates provided by the tablet, and get triggered when a specific amount of lines is moved, no matter the area used.

Not exactly sure how to troubleshoot this at this point.

## New Plans

Coming back to the original issue, Here is what I'm gonna add to my plans : 

- In-app, Gesture debugger, So i don't have to remote debug & place logpoints on every gestures,
- Write more testing procedure,
- Document the intended behavior of the UX,
- Document the intended behavior of each gestures,
- Investigate the scrolling behavior on more distros (Send Help), than just Raspi OS (Debian) & Mint (Ubuntu -> Debian).

Once the issue is identified, here is how I'm gonna proceed :

- Fix Touch fix, do further testing, then request for testing from others,
- Proceed the same way, for pen inputs.

There will be probably more to come, but for now, that's what i have in mind, that & the 5h of sleep, that is.
(US-like Schedule reset hit hard)

**Comment by xSamel-The-Camelx** [comment]
>Investigate the scrolling behavior on more distros (Send Help), than just Raspi OS (Debian) & Mint (Ubuntu -> Debian).

I can distro hop through any you need testing done on. Is there anything other than just the scrolling behavior you would like me to test? I am fine with testing stuff unrelated to this if you like.

My current outline on what I plan to test is
Every major DE on whatever distro that implements them is most popular ie Gnome on Ubuntu
At least every Major distro ie Ubuntu, Fedora, Arch

That should leave me testing on
Ubuntu
Mint with Cinnamon
Fedora
openSUSE
Arch linux (prob just just with kde)

If Raspi OS works on regular hardware I can test that for you too

If there are any other distros you would like me to test on please let me know.
I will probably start testing on ether the 25th or the 2nd.

**Comment by Mrcubix** [comment]
One of my install is Mint with cinamon, but it's possible things changed is newer versions, so prob worth investigating that

**Comment by Mrcubix** [comment]
Finally managed to get a arch install working, and was unable to get the same behavior, 
Will still proceed with the TODO whenever i have time as I'm preparing to start working in January.

**Comment by xSamel-The-Camelx** [comment]
Sorry for long time to reply. But the issue with inconsistent scrolling seems to be gone now. Scrolling did stop working for me entirely for a little bit, but after looking into that its just the legacy scrolling. After setting up the new scrolling it works better than ever for me.

But now scrolling no longer works at all with touch gestures. and the touch gestures ux wouldnt even open with "Enable Legacy Scroll Bindings Settings" checked on with this error popping up in my console:
```
An Error occured while attempting to connect to the RPC server: Object reference not set to an instance of an object.
----------------------------------------
This error could have occured due to an different version of WheelAddon being used with this Interface.

```
I dont have wheel addon installed btw.

Once I could ajust my touch gestures I tried to test scroll bound to pan. both the legacy and new function visually do nothing in firefox. but in my terminal they do show the input. idk if its scrolling with zero distance or what. I didnt try fiddleing with settings to get it working

**Comment by Mrcubix** [comment]
Scroll binding starts a timer that trigger a scroll at various intervals.

Touch gestures only holds a key for 15 ms when the pan threshold us reached.

That means if your interval is >= 15 ms,
Then it probably won't trigger.

As a side note, Scroll Binding itself sends REL_WHEEL_HI_RES (or H for the horizontal variant).
